import { Routes } from '@angular/router';
import { HomeComponent } from './pages/home/home.component';
import { LoginComponent } from './auth/login/login.component';
import { RegisterComponent } from './auth/register/register.component';
import { DashboardComponent } from './pages/dashboard/dashboard.component';
import { ProfileComponent } from './pages/profile/profile.component';
import { CloudStorageComponent } from './pages/CloudServices/cloud-storage/cloud-storage.component';
import { ClustersComponent } from './pages/CloudServices/clusters/clusters.component';
import { VpcsComponent } from './pages/CloudServices/vpcs/vpcs.component';
import { EcrComponent } from './pages/CloudServices/ecr/ecr.component';
import { EcsComponent } from './pages/CloudServices/ecs/ecs.component';
import { SubnetsComponent } from './pages/CloudServices/subnets/subnets.component';
import { SecurityGroupsComponent } from './pages/CloudServices/security-groups/security-groups.component';
import { CloudWatchLogsComponent } from './pages/CloudServices/cloudwatch-logs/cloudwatch-logs.component';
import { Ec2InstancesComponent } from './pages/CloudServices/ec2-instances/ec2-instances.component';
import { LaunchInstanceComponent } from './pages/CloudServices/ec2-instances/launch-instance/launch-instance.component';
import { CreateBucketComponent } from './pages/CloudServices/cloud-storage/create-bucket/create-bucket.component';
import { BucketOverviewComponent } from './pages/CloudServices/cloud-storage/bucket-overview/bucket-overview.component';
import { SearchResultsComponent } from './global-search/search-results.component';
import { ClusterOverviewComponent } from './pages/CloudServices/clusters/cluster-overview/cluster-overview.component';
import { CreateClusterComponent } from './pages/CloudServices/clusters/create-cluster/create-cluster.component';
import { CreateVpcComponent } from './pages/CloudServices/vpcs/create-vpc/create-vpc.component';
import { VpcOverviewComponent } from './pages/CloudServices/vpcs/vpc-overview/vpc-overview.component';
import { EcsOverviewComponent } from './pages/CloudServices/ecs/ecs-overview/ecs-overview.component';
import { CreateEcsServiceComponent } from './pages/CloudServices/ecs/create-ecs-service/create-ecs-service.component';
import { CreateTaskDefinitionComponent } from './pages/CloudServices/ecs/create-task-definition/create-task-definition.component';
import { CreateSecurityGroupComponent } from './pages/CloudServices/security-groups/create-security-group/create-security-group.component';
import { CreateSubnetComponent } from './pages/CloudServices/subnets/create-subnet/create-subnet.component';
import { SubnetOverviewComponent } from './pages/CloudServices/subnets/subnet-overview/subnet-overview.component';
import { SecurityGroupOverviewComponent } from './pages/CloudServices/security-groups/security-group-overview/security-group-overview.component';
import { Ec2OverviewComponent } from './pages/CloudServices/ec2-instances/ec2-overview/ec2-overview.component';
import { Ec2ConnectComponent } from './pages/CloudServices/ec2-instances/ec2-connect/ec2-connect.component';
import { Ec2QuickConnectComponent } from './pages/CloudServices/ec2-instances/ec2-quick-connect/ec2-quick-connect.component';
import { PermissionsComponent } from './pages/CloudServices/permissions/permissions.component';
import { KeyPairsComponent } from './pages/key-pairs/key-pairs.component';
import { KeyPairOverviewComponent } from './pages/key-pairs/key-pair-overview/key-pair-overview.component';
import { CreateKeyPairComponent } from './pages/key-pairs/create-key-pair/create-key-pair.component';
import { SensitiveDataViewerComponent } from './pages/key-pairs/sensitive-data-viewer/sensitive-data-viewer.component';
import { InternetGatewaysComponent } from './pages/CloudServices/internet-gateways/internet-gateways.component';
import { CreateInternetGatewayComponent } from './pages/CloudServices/internet-gateways/create-internet-gateway/create-internet-gateway.component';
import { InternetGatewayOverviewComponent } from './pages/CloudServices/internet-gateways/internet-gateway-overview/internet-gateway-overview.component';
import { ResourceGraphDashboardComponent } from './pages/CloudServices/resource-graph/resource-graph-dashboard/resource-graph-dashboard.component';
import { VpcTreeViewComponent } from './pages/CloudServices/resource-graph/vpc-tree-view/vpc-tree-view.component';
import { DependenciesExplorerComponent } from './pages/CloudServices/resource-graph/dependencies-explorer/dependencies-explorer.component';
import { DeletionBlockersComponent } from './pages/CloudServices/resource-graph/deletion-blockers/deletion-blockers.component';
import { VpcNetworkInfoComponent } from './pages/CloudServices/resource-graph/vpc-network-info/vpc-network-info.component';

export const routes: Routes = [
  { path: '', component: HomeComponent },
  { path: 'login', component: LoginComponent },
  { path: 'register', component: RegisterComponent },
  { path: 'search', component: SearchResultsComponent },
  { path: 'dashboard', component: DashboardComponent },
  { path: 'dashboard/cloud-storage', component: CloudStorageComponent },
  { path: 'dashboard/cloud-storage/create', component: CreateBucketComponent },
  { path: 'dashboard/cloud-storage/:id', component: BucketOverviewComponent },
  { path: 'dashboard/clusters', component: ClustersComponent },
  { path: 'dashboard/clusters/create', component: CreateClusterComponent },
  { path: 'dashboard/clusters/:id', component: ClusterOverviewComponent },
  { path: 'dashboard/vpcs', component: VpcsComponent },
  { path: 'dashboard/vpcs/create', component: CreateVpcComponent },
  { path: 'dashboard/vpcs/:id', component: VpcOverviewComponent },
  { path: 'dashboard/ecr', component: EcrComponent },
  { path: 'dashboard/ecs', component: EcsComponent },
  { path: 'dashboard/ecs/create', component: CreateEcsServiceComponent },
  { path: 'dashboard/ecs/create-task-definition', component: CreateTaskDefinitionComponent },
  { path: 'dashboard/ecs/:id', component: EcsOverviewComponent },
  { path: 'dashboard/subnets/create', component: CreateSubnetComponent },
  { path: 'dashboard/subnets/:id', component: SubnetOverviewComponent },
  { path: 'dashboard/subnets', component: SubnetsComponent },
  { path: 'dashboard/security-groups/create', component: CreateSecurityGroupComponent },
  { path: 'dashboard/security-groups/:id', component: SecurityGroupOverviewComponent },
  { path: 'dashboard/security-groups', component: SecurityGroupsComponent },
  { path: 'dashboard/cloudwatch-logs', component: CloudWatchLogsComponent },
  { path: 'dashboard/ec2-instances/create', component: LaunchInstanceComponent },
  { path: 'dashboard/ec2-instances/:id/connect', component: Ec2ConnectComponent },
  { path: 'dashboard/quick-connect', component: Ec2QuickConnectComponent },
  { path: 'dashboard/ec2-instances/:id', component: Ec2OverviewComponent },
  { path: 'dashboard/ec2-instances', component: Ec2InstancesComponent },
  { path: 'dashboard/permissions', component: PermissionsComponent },
  { path: 'dashboard/internet-gateways', component: InternetGatewaysComponent },
  { path: 'dashboard/internet-gateways/create', component: CreateInternetGatewayComponent },
  { path: 'dashboard/internet-gateways/:id', component: InternetGatewayOverviewComponent },
  { path: 'dashboard/resource-graph', component: ResourceGraphDashboardComponent },
  { path: 'dashboard/resource-graph/vpc/:vpcId', component: VpcTreeViewComponent },
  { path: 'dashboard/resource-graph/dependencies', component: DependenciesExplorerComponent },
  { path: 'dashboard/resource-graph/deletion-blockers', component: DeletionBlockersComponent },
  { path: 'dashboard/resource-graph/vpc-network/:vpcId', component: VpcNetworkInfoComponent },
  { path: 'dashboard/key-pairs/create', component: CreateKeyPairComponent },
  { path: 'dashboard/key-pairs/:id/private-key', component: SensitiveDataViewerComponent },
  { path: 'dashboard/key-pairs/:id', component: KeyPairOverviewComponent },
  { path: 'dashboard/key-pairs', component: KeyPairsComponent },
  { path: 'profile', component: ProfileComponent },
  { path: '**', redirectTo: '' }
];